# Copyright (C) 2022 Nippon Telegraph and Telephone Corporation.
#
# This software is released under the MIT License.
# http://opensource.org/licenses/mit-license.php

name: PyTest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r lfsccm/requirements.txt
        python -m pip install -r lfsccm/test-requirements.txt
    - name: Test with nose2
      run: |
        python -m nose2
      working-directory: lfsccm
